version: '3'

services:
  postgres:
    image: postgres:12.1
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
