version: '3'

services:
  postgres:
    image: postgres:12.1
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    maw:
      image: maw
      ports:
        - 8080:8080
      env_file:
        - maw.env

volumes:
  postgres-data:
    driver: local
