server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  codec:
    max-in-memory-size: 4MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    pl.pwr.maw: info

api:
  webPageTestUrl: http://www.webpagetest.org/runtest.php
  webPageTestLocationsUrl: http://www.webpagetest.org/getLocations.php
  pageSpeedInsightsUrl: https://www.googleapis.com/pagespeedonline/v5/runPagespeed
